name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2020.3.0f1 # 使用しているUnityのバージョンに変更

      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL # WebGLビルドのディレクトリに変更
